name: "yet_another_todo"

version: "1.0.0+1"
publish_to: none

environment:
  sdk: ">=3.4.0 <4.0.0"

description: A new Flutter project.

dependencies:
  bloc: ^8.1.4
  cupertino_icons: "^1.0.6"

  dio: ^5.4.3+1
  drift: ^2.18.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_dotenv: ^5.1.0
  flutter_launcher_icons: "^0.13.1"
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: "^2.4.0"
  flutter_svg: "^2.0.10+1"

  freezed: ^2.5.2
  freezed_annotation: ^2.4.1
  intl: "^0.19.0"
  json_annotation: ^4.9.0
  logger: "^2.3.0"
  path: ^1.9.0
  path_provider: ^2.1.3
  sqlite3: ^2.4.4
  sqlite3_flutter_libs: ^0.5.24
  url_launcher: "^6.3.0"
  uuid: ^4.4.0

dev_dependencies:
  build_runner: ^2.4.11
  drift_dev: ^2.18.0
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - config.env
    - assets/icons/
    - assets/app/

flutter_launcher_icons:
  image_path: "assets/app/yet_another_icon.png"
  android: true
  min_sdk_android: 21
  ios: true

flutter_native_splash:
  image: "assets/app/yet_another_splash.jpg"
  color: "#000000"
  android: true
  ios: true

  android_12:
    image: "assets/app/yet_another_splash.jpg"
