name: "yet_another_todo"

version: "1.0.0+1"
publish_to: none

environment:
  sdk: ">=3.4.0 <4.0.0"

description: A new Flutter project.

dependencies:
  cupertino_icons: "^1.0.6"

  flutter:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: "^2.4.0"
  flutter_svg: "^2.0.10+1"

  intl: "^0.19.0"
  logger: "^2.3.0"
  url_launcher: "^6.3.0"

dev_dependencies:
  flutter_lints: "^3.0.0"
  flutter_test:
    sdk: flutter
  surf_lint_rules: ^1.3.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/app/

flutter_launcher_icons:
  image_path: "assets/app/yet_another_icon.png"
  android: true
  min_sdk_android: 21
  ios: true

flutter_native_splash:
  image: "assets/app/yet_another_splash.jpg"
  color: "#000000"
  android: true
  ios: true

  android_12:
    image: "assets/app/yet_another_splash.jpg"
