name: yet_another_todo
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6
  logger: ^2.3.0
  intl: ^0.19.0
  flutter_svg: ^2.0.10+1
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/app/

# ------- App Icons Config:
flutter_launcher_icons:
  image_path: "assets/app/yet_another_icon.png"

  android: true
  min_sdk_android: 21 # android min sdk min:16, default 21

  ios: true

flutter_native_splash:
  image: "assets/app/yet_another_splash.jpg"

  color: "#000000"
  android: true
  ios: true

  android_12:
    image: assets/app/yet_another_splash.jpg
