name: Flutter CI

on:
  pull_request:
    branches:
      - main

jobs:
  analyze:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - uses: ./.github/actions/init_flutter
      - run: flutter analyze --no-fatal-infos

  format:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - uses: ./.github/actions/init_flutter
      - run: dart format --set-exit-if-changed .

  test:
    timeout-minutes: 10
    needs: [format, analyze]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - uses: ./.github/actions/init_flutter
      - run: flutter test

  build:
    timeout-minutes: 18
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17
      - uses: ./.github/actions/init_flutter
      - run: flutter build apk --dart-define=API_BASE_URL=${{ secrets.API_BASE_URL }} --dart-define=API_TOKEN=${{ secrets.API_TOKEN }} --split-per-abi
      - name: Upload APK to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/app/outputs/flutter-apk/app-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
