name: Flutter CI

on:
  pull_request:
    branches:
      - main

jobs:
  analyze:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter gen-l10n
      - run: dart run build_runner build --delete-conflicting-outputs

      - run: touch config.env
      - run: echo "API_BASE_URL=${{ secrets.API_BASE_URL }}" >> config.env
      - run: echo "API_TOKEN=${{ secrets.API_TOKEN }}" >> config.env

      - run: flutter analyze --no-fatal-infos

  format:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter gen-l10n
      - run: dart run build_runner build --delete-conflicting-outputs
      - run: dart format --set-exit-if-changed .

  test:
    timeout-minutes: 10
    needs: [format, analyze]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter test

  build:
    timeout-minutes: 10
    needs: [test]
    runs-on: ubuntu-latest
    env:
      API_BASE_URL: ${{ secrets.API_BASE_URL }}
      API_TOKEN: ${{ secrets.API_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: "17"
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - run: flutter pub get

      - run: flutter gen-l10n
      - run: dart run build_runner build --delete-conflicting-outputs

      - run: touch config.env
      - run: echo "API_BASE_URL=${{ secrets.API_BASE_URL }}" >> config.env
      - run: echo "API_TOKEN=${{ secrets.API_TOKEN }}" >> config.env

      - run: flutter build apk --dart-define=API_BASE_URL=${{ secrets.API_BASE_URL }} --dart-define=API_TOKEN=${{ secrets.API_TOKEN }} --split-per-abi

      - name: Upload APK to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/app/outputs/flutter-apk/app-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
